name: Build pricing-service

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-deploy:
    uses: dcSpark/pricing-service/.github/workflows/build-workflow.yml@main
    with:
      REGISTRY: dcspark
      REPOSITORY: pricing-service
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
